services:
  - type: web
    name: madrasa-qurania
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node server.mjs
    envVars:
      - key: NODE_ENV
        value: production
    nodeVersion: 22
